# Generated by Django 4.0.4 on 2022-04-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_feed_email_alter_feed_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['feed_id'], name='content_lik_feed_id_d49208_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['email'], name='content_lik_email_091bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['feed_id'], name='content_boo_feed_id_0d6861_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['email'], name='content_boo_email_03c3c8_idx'),
        ),
    ]
